name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main  # ドキュメントをデプロイしたいブランチ

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # お好きなPythonのバージョンを指定

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme  # Sphinxとテーマをインストール

    - name: Build the documentation
      run: |
        cd docs  # Sphinxプロジェクトのディレクトリに移動
        make html  # HTMLドキュメントをビルド

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html  # ビルドしたHTMLのディレクトリ
        publish_branch: gh-pages  # GitHub Pagesのブランチ
